FROM rust:1.92-alpine3.20 AS atc-router

ADD . .

ARG ARTIFACT_NAME=libatc_router-snapshot-alpine3.20.tar.gz

RUN apk update && \
  apk add bash curl git build-base && \
  make build-deps

RUN tar -zcvf ${ARTIFACT_NAME} libatc_router.* && \
  mkdir -p /out && \
  cp ${ARTIFACT_NAME} /out/